### Rota para pegar os produtos
GET http://localhost:3001/produtos

### fechando a requicisao

### Rota criando o produto
POST http://localhost:3001/produtos
Content-Type: application/json

{
    "id":1,
    "nome":"GTX 4090 24gb",
    "preco":14450
}