### Rota para pegar os produtos
GET http://localhost:3000/produtos

### fechando a requicisao

### Rota criando o produto
POST http://localhost:3000/produtos
Content-Type: application/json

{
    "id":"1",
    "nome":"GTX 4090 24gb",
    "preco":14450
}

### 

###pegar produto pelo id
GET http://localhost:3000/produtos/1
Content-Type: application/json


### PUT -Editar produto 
PUT http://localhost:3000/produto/1
Content-Type: application/json

{
    "novoNome": "GTX 3080 16gb",
    "novoPreco": 12000
}

###


###DELETE - DELETAR OS PRODUTOS
DELETE http://localhost:3000/produtos/1
Content-Type: application/json


### 

### DELETE -Excluido todos os produtos
DELETE http://localhost:3000/produtos
Content-Type:application/json

